#  The workflow allows running tests, code checkstyle and security scans on feature branches (as well as master).

image: atlassian/default-image:2

# Workflow Configuration
definitions:
  services:
    docker:
      memory: 2024

  steps:
    - step: &BUILD
        name: build
        image: node:24
        script:
          - chmod 755 build/*.sh
          - ./build/package.sh wrenchiq
        artifacts:
          - bin/wrenchiq.tar.gz

    - step: &BINARY
        fail-fast: true
        name: binary
        image: atlassian/default-image:2
        script:
          - chmod 755 build/*.sh
          - ./build/binary.sh wrenchiq
        artifacts:
          - bin/wrenchiq/**

    - step: &DEPLOY_DEV_WRENCHIQ
        name: Deploy [DEV_WRENCHIQ]
        image:
          name: prediibitbucket.azurecr.io/predii-azcopy:latest
          username: $ACR_USERNAME
          password: $ACR_PASSWORD
        trigger: manual
        deployment: DEV_WRENCHIQ
        script:
          - chmod 755 build/*.sh
          - ./build/deploy.sh DEV wrenchiq
          - bash build/trigger_k8s.sh DEV

    - step: &DEPLOY_UAT_WRENCHIQ
        name: Deploy [UAT_WRENCHIQ]
        image: atlassian/default-image:4
        trigger: manual
        deployment: UAT_WRENCHIQ
        script:
          - chmod 755 build/trigger_k8s.sh
 #         - bash build/trigger_k8s.sh UAT

    - step: &DEPLOY_PROD_WRENCHIQ
        name: Deploy [PROD_WRENCHIQ]
        image: atlassian/default-image:4
        trigger: manual
        deployment: PROD_WRENCHIQ
        script:
          - chmod 755 build/trigger_k8s.sh
 #         - bash build/trigger_k8s.sh PROD

pipelines:
  branches:
    main:
      - step: *BUILD

  pull-requests:
    "**":
      - step: *BUILD

  tags:
    "*":
      - step: *BUILD
      - step: *BINARY
      - parallel:
          steps:
            - step: *DEPLOY_DEV_WRENCHIQ
            - step: *DEPLOY_UAT_WRENCHIQ
            - step: *DEPLOY_PROD_WRENCHIQ
