/**
 * WrenchIQ — Seed DVI Samples onto Story ROs
 *
 * One-time seed: attaches the synthetic DVI reports generated by
 * scripts/simulateDviForQueue.js (resources/dvi_samples/RO-*.json) onto
 * their matching RepairOrder docs' `dviInspection` field, so the Sidecar's
 * inspection-findings dropdown (WrenchIQSidecarScreen.jsx) has real data
 * to read via GET /api/repair-orders/story-ro/:roId.
 *
 * Usage:
 *   node --env-file=.env.local scripts/seedDviSamples.js
 */

import { MongoClient } from 'mongodb';
import { readdirSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DVI_DIR = join(__dirname, '..', 'resources', 'dvi_samples');

const MONGODB_URI = process.env.MONGODB_URI;
const MONGODB_DB = process.env.MONGODB_DB;

if (!MONGODB_URI || !MONGODB_DB) {
  console.error('MONGODB_URI/MONGODB_DB must be set — run with: node --env-file=.env.local scripts/seedDviSamples.js');
  process.exit(1);
}

async function main() {
  const files = readdirSync(DVI_DIR).filter((f) => f.endsWith('.json') && f !== '_manifest.json');

  const client = new MongoClient(MONGODB_URI);
  await client.connect();
  const db = client.db(MONGODB_DB);

  for (const file of files) {
    const roNumber = file.replace(/\.json$/, '');
    const dviInspection = JSON.parse(readFileSync(join(DVI_DIR, file), 'utf8'));

    const result = await db.collection('RepairOrder').updateOne(
      { roNumber, isStoryRO: true },
      { $set: { dviInspection, updatedAt: new Date().toISOString() } }
    );

    const urgentCount = (dviInspection.categories || [])
      .flatMap((c) => c.items || [])
      .filter((i) => i.status === 'urgent').length;

    if (result.matchedCount === 0) {
      console.log(`  [skip] ${roNumber}: no matching story RO found`);
    } else {
      console.log(`  [ok] ${roNumber}: dviInspection set (${urgentCount} urgent item(s))`);
    }
  }

  await client.close();
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
